/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_CR_LF = 1,
  anon_sym_CR = 2,
  anon_sym_LF = 3,
  anon_sym_DOT = 4,
  anon_sym_SEMI = 5,
  anon_sym_COLON = 6,
  aux_sym_group_token1 = 7,
  sym_property_value = 8,
  anon_sym_EQ = 9,
  anon_sym_COMMA = 10,
  aux_sym_parameter_value_token1 = 11,
  aux_sym_parameter_value_token2 = 12,
  sym_source_file = 13,
  sym__crlf = 14,
  sym_property = 15,
  sym_group = 16,
  sym_property_name = 17,
  sym_parameter = 18,
  sym_parameter_name = 19,
  sym_parameter_value = 20,
  aux_sym_source_file_repeat1 = 21,
  aux_sym_source_file_repeat2 = 22,
  aux_sym_property_repeat1 = 23,
  aux_sym_parameter_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_CR] = "\r",
  [anon_sym_LF] = "\n",
  [anon_sym_DOT] = ".",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [aux_sym_group_token1] = "group_token1",
  [sym_property_value] = "property_value",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [aux_sym_parameter_value_token1] = "parameter_value_token1",
  [aux_sym_parameter_value_token2] = "parameter_value_token2",
  [sym_source_file] = "source_file",
  [sym__crlf] = "_crlf",
  [sym_property] = "property",
  [sym_group] = "group",
  [sym_property_name] = "property_name",
  [sym_parameter] = "parameter",
  [sym_parameter_name] = "parameter_name",
  [sym_parameter_value] = "parameter_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_property_repeat1] = "property_repeat1",
  [aux_sym_parameter_repeat1] = "parameter_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_CR] = anon_sym_CR,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_group_token1] = aux_sym_group_token1,
  [sym_property_value] = sym_property_value,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_parameter_value_token1] = aux_sym_parameter_value_token1,
  [aux_sym_parameter_value_token2] = aux_sym_parameter_value_token2,
  [sym_source_file] = sym_source_file,
  [sym__crlf] = sym__crlf,
  [sym_property] = sym_property,
  [sym_group] = sym_group,
  [sym_property_name] = sym_property_name,
  [sym_parameter] = sym_parameter,
  [sym_parameter_name] = sym_parameter_name,
  [sym_parameter_value] = sym_parameter_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_property_repeat1] = aux_sym_property_repeat1,
  [aux_sym_parameter_repeat1] = aux_sym_parameter_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_group_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_property_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_parameter_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__crlf] = {
    .visible = false,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_property_name] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_name] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_property_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 16,
  [35] = 18,
  [36] = 19,
  [37] = 21,
  [38] = 32,
  [39] = 23,
  [40] = 29,
  [41] = 27,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 42,
  [46] = 46,
  [47] = 47,
  [48] = 46,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 51,
  [54] = 50,
  [55] = 49,
  [56] = 56,
  [57] = 57,
  [58] = 52,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == ',') ADVANCE(16);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '=') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '"') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(1);
      if (lookahead > ' ' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead > 0x1f) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead > 0x1f &&
          lookahead != '"') ADVANCE(2);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(4);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(7);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(7);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_group_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_property_value);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_property_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_parameter_value_token1);
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead > ' ' &&
          lookahead != '"' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_parameter_value_token1);
      if (lookahead > 0x1f &&
          lookahead != '"' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_parameter_value_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 13},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 13},
  [49] = {.lex_state = 13},
  [50] = {.lex_state = 13},
  [51] = {.lex_state = 13},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 13},
  [54] = {.lex_state = 13},
  [55] = {.lex_state = 13},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_group_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_parameter_value_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(56),
    [sym__crlf] = STATE(2),
    [sym_property] = STATE(7),
    [sym_group] = STATE(52),
    [sym_property_name] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_source_file_repeat2] = STATE(15),
    [anon_sym_CR_LF] = ACTIONS(3),
    [anon_sym_CR] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(3),
    [aux_sym_group_token1] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(5), 1,
      aux_sym_group_token1,
    STATE(10), 1,
      sym_property,
    STATE(14), 1,
      aux_sym_source_file_repeat2,
    STATE(32), 1,
      sym_property_name,
    STATE(52), 1,
      sym_group,
    STATE(8), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [25] = 4,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      aux_sym_group_token1,
    STATE(6), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [41] = 4,
    ACTIONS(13), 1,
      aux_sym_group_token1,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(6), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [57] = 4,
    ACTIONS(13), 1,
      aux_sym_group_token1,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(6), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [73] = 4,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(24), 1,
      aux_sym_group_token1,
    STATE(6), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
    ACTIONS(21), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [89] = 3,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    STATE(4), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
    ACTIONS(28), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [102] = 3,
    ACTIONS(24), 1,
      aux_sym_group_token1,
    STATE(8), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
    ACTIONS(30), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [115] = 3,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(5), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
    ACTIONS(33), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [128] = 3,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(3), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
    ACTIONS(35), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [141] = 3,
    ACTIONS(13), 1,
      aux_sym_group_token1,
    STATE(8), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
    ACTIONS(7), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [154] = 2,
    STATE(11), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
    ACTIONS(37), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [164] = 5,
    ACTIONS(39), 1,
      aux_sym_group_token1,
    STATE(12), 1,
      sym_property,
    STATE(13), 1,
      aux_sym_source_file_repeat2,
    STATE(38), 1,
      sym_property_name,
    STATE(58), 1,
      sym_group,
  [180] = 5,
    ACTIONS(42), 1,
      aux_sym_group_token1,
    STATE(9), 1,
      sym_property,
    STATE(13), 1,
      aux_sym_source_file_repeat2,
    STATE(32), 1,
      sym_property_name,
    STATE(52), 1,
      sym_group,
  [196] = 5,
    ACTIONS(42), 1,
      aux_sym_group_token1,
    STATE(10), 1,
      sym_property,
    STATE(13), 1,
      aux_sym_source_file_repeat2,
    STATE(32), 1,
      sym_property_name,
    STATE(52), 1,
      sym_group,
  [212] = 2,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [221] = 3,
    ACTIONS(50), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym_parameter_repeat1,
    ACTIONS(48), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [232] = 2,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [241] = 2,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [250] = 3,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      aux_sym_parameter_repeat1,
    ACTIONS(61), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [261] = 2,
    ACTIONS(65), 1,
      ts_builtin_sym_end,
    ACTIONS(67), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [270] = 3,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym_parameter_repeat1,
    ACTIONS(69), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [281] = 3,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    ACTIONS(73), 1,
      anon_sym_COLON,
    STATE(24), 1,
      aux_sym_property_repeat1,
  [291] = 3,
    ACTIONS(75), 1,
      anon_sym_SEMI,
    ACTIONS(78), 1,
      anon_sym_COLON,
    STATE(24), 1,
      aux_sym_property_repeat1,
  [301] = 3,
    ACTIONS(80), 1,
      aux_sym_group_token1,
    STATE(44), 1,
      sym_parameter,
    STATE(57), 1,
      sym_parameter_name,
  [311] = 2,
    ACTIONS(82), 1,
      anon_sym_DOT,
    ACTIONS(84), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [319] = 3,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    ACTIONS(86), 1,
      anon_sym_COLON,
    STATE(24), 1,
      aux_sym_property_repeat1,
  [329] = 3,
    ACTIONS(88), 1,
      aux_sym_parameter_value_token1,
    ACTIONS(90), 1,
      aux_sym_parameter_value_token2,
    STATE(20), 1,
      sym_parameter_value,
  [339] = 3,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    ACTIONS(92), 1,
      anon_sym_COLON,
    STATE(27), 1,
      aux_sym_property_repeat1,
  [349] = 1,
    ACTIONS(94), 3,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_COMMA,
  [355] = 3,
    ACTIONS(88), 1,
      aux_sym_parameter_value_token1,
    ACTIONS(90), 1,
      aux_sym_parameter_value_token2,
    STATE(33), 1,
      sym_parameter_value,
  [365] = 3,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    ACTIONS(96), 1,
      anon_sym_COLON,
    STATE(23), 1,
      aux_sym_property_repeat1,
  [375] = 1,
    ACTIONS(48), 3,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_COMMA,
  [381] = 1,
    ACTIONS(46), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [387] = 1,
    ACTIONS(55), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [393] = 1,
    ACTIONS(59), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [399] = 1,
    ACTIONS(67), 3,
      anon_sym_CR_LF,
      anon_sym_CR,
      anon_sym_LF,
  [405] = 3,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    ACTIONS(98), 1,
      anon_sym_COLON,
    STATE(39), 1,
      aux_sym_property_repeat1,
  [415] = 3,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    ACTIONS(100), 1,
      anon_sym_COLON,
    STATE(24), 1,
      aux_sym_property_repeat1,
  [425] = 3,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    ACTIONS(102), 1,
      anon_sym_COLON,
    STATE(41), 1,
      aux_sym_property_repeat1,
  [435] = 3,
    ACTIONS(71), 1,
      anon_sym_SEMI,
    ACTIONS(104), 1,
      anon_sym_COLON,
    STATE(24), 1,
      aux_sym_property_repeat1,
  [445] = 2,
    ACTIONS(106), 1,
      aux_sym_group_token1,
    STATE(29), 1,
      sym_property_name,
  [452] = 1,
    ACTIONS(84), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [457] = 1,
    ACTIONS(78), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [462] = 2,
    ACTIONS(106), 1,
      aux_sym_group_token1,
    STATE(40), 1,
      sym_property_name,
  [469] = 1,
    ACTIONS(108), 1,
      sym_property_value,
  [473] = 1,
    ACTIONS(110), 1,
      anon_sym_EQ,
  [477] = 1,
    ACTIONS(112), 1,
      sym_property_value,
  [481] = 1,
    ACTIONS(114), 1,
      sym_property_value,
  [485] = 1,
    ACTIONS(116), 1,
      sym_property_value,
  [489] = 1,
    ACTIONS(118), 1,
      sym_property_value,
  [493] = 1,
    ACTIONS(120), 1,
      anon_sym_DOT,
  [497] = 1,
    ACTIONS(122), 1,
      sym_property_value,
  [501] = 1,
    ACTIONS(124), 1,
      sym_property_value,
  [505] = 1,
    ACTIONS(126), 1,
      sym_property_value,
  [509] = 1,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
  [513] = 1,
    ACTIONS(130), 1,
      anon_sym_EQ,
  [517] = 1,
    ACTIONS(132), 1,
      anon_sym_DOT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 41,
  [SMALL_STATE(5)] = 57,
  [SMALL_STATE(6)] = 73,
  [SMALL_STATE(7)] = 89,
  [SMALL_STATE(8)] = 102,
  [SMALL_STATE(9)] = 115,
  [SMALL_STATE(10)] = 128,
  [SMALL_STATE(11)] = 141,
  [SMALL_STATE(12)] = 154,
  [SMALL_STATE(13)] = 164,
  [SMALL_STATE(14)] = 180,
  [SMALL_STATE(15)] = 196,
  [SMALL_STATE(16)] = 212,
  [SMALL_STATE(17)] = 221,
  [SMALL_STATE(18)] = 232,
  [SMALL_STATE(19)] = 241,
  [SMALL_STATE(20)] = 250,
  [SMALL_STATE(21)] = 261,
  [SMALL_STATE(22)] = 270,
  [SMALL_STATE(23)] = 281,
  [SMALL_STATE(24)] = 291,
  [SMALL_STATE(25)] = 301,
  [SMALL_STATE(26)] = 311,
  [SMALL_STATE(27)] = 319,
  [SMALL_STATE(28)] = 329,
  [SMALL_STATE(29)] = 339,
  [SMALL_STATE(30)] = 349,
  [SMALL_STATE(31)] = 355,
  [SMALL_STATE(32)] = 365,
  [SMALL_STATE(33)] = 375,
  [SMALL_STATE(34)] = 381,
  [SMALL_STATE(35)] = 387,
  [SMALL_STATE(36)] = 393,
  [SMALL_STATE(37)] = 399,
  [SMALL_STATE(38)] = 405,
  [SMALL_STATE(39)] = 415,
  [SMALL_STATE(40)] = 425,
  [SMALL_STATE(41)] = 435,
  [SMALL_STATE(42)] = 445,
  [SMALL_STATE(43)] = 452,
  [SMALL_STATE(44)] = 457,
  [SMALL_STATE(45)] = 462,
  [SMALL_STATE(46)] = 469,
  [SMALL_STATE(47)] = 473,
  [SMALL_STATE(48)] = 477,
  [SMALL_STATE(49)] = 481,
  [SMALL_STATE(50)] = 485,
  [SMALL_STATE(51)] = 489,
  [SMALL_STATE(52)] = 493,
  [SMALL_STATE(53)] = 497,
  [SMALL_STATE(54)] = 501,
  [SMALL_STATE(55)] = 505,
  [SMALL_STATE(56)] = 509,
  [SMALL_STATE(57)] = 513,
  [SMALL_STATE(58)] = 517,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [24] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(26),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 5, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 5, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 6, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 6, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_property_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_property_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_name, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_value, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_name, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [128] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vcard(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "vcard",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
