/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_CR_LF = 1,
  anon_sym_DOT = 2,
  anon_sym_SEMI = 3,
  anon_sym_COLON = 4,
  aux_sym_group_token1 = 5,
  aux_sym_property_value_token1 = 6,
  anon_sym_CR_LF2 = 7,
  anon_sym_CR_LF_TAB = 8,
  anon_sym_EQ = 9,
  anon_sym_COMMA = 10,
  aux_sym_parameter_value_token1 = 11,
  aux_sym_parameter_value_token2 = 12,
  sym_source_file = 13,
  sym_property = 14,
  sym_group = 15,
  sym_property_name = 16,
  sym_property_value = 17,
  sym_parameter = 18,
  sym_parameter_name = 19,
  sym_parameter_value = 20,
  aux_sym_source_file_repeat1 = 21,
  aux_sym_property_repeat1 = 22,
  aux_sym_property_value_repeat1 = 23,
  aux_sym_parameter_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_DOT] = ".",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [aux_sym_group_token1] = "group_token1",
  [aux_sym_property_value_token1] = "property_value_token1",
  [anon_sym_CR_LF2] = "\r\n ",
  [anon_sym_CR_LF_TAB] = "\r\n\t",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [aux_sym_parameter_value_token1] = "parameter_value_token1",
  [aux_sym_parameter_value_token2] = "parameter_value_token2",
  [sym_source_file] = "source_file",
  [sym_property] = "property",
  [sym_group] = "group",
  [sym_property_name] = "property_name",
  [sym_property_value] = "property_value",
  [sym_parameter] = "parameter",
  [sym_parameter_name] = "parameter_name",
  [sym_parameter_value] = "parameter_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_property_repeat1] = "property_repeat1",
  [aux_sym_property_value_repeat1] = "property_value_repeat1",
  [aux_sym_parameter_repeat1] = "parameter_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_group_token1] = aux_sym_group_token1,
  [aux_sym_property_value_token1] = aux_sym_property_value_token1,
  [anon_sym_CR_LF2] = anon_sym_CR_LF2,
  [anon_sym_CR_LF_TAB] = anon_sym_CR_LF_TAB,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_parameter_value_token1] = aux_sym_parameter_value_token1,
  [aux_sym_parameter_value_token2] = aux_sym_parameter_value_token2,
  [sym_source_file] = sym_source_file,
  [sym_property] = sym_property,
  [sym_group] = sym_group,
  [sym_property_name] = sym_property_name,
  [sym_property_value] = sym_property_value,
  [sym_parameter] = sym_parameter,
  [sym_parameter_name] = sym_parameter_name,
  [sym_parameter_value] = sym_parameter_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_property_repeat1] = aux_sym_property_repeat1,
  [aux_sym_property_value_repeat1] = aux_sym_property_value_repeat1,
  [aux_sym_parameter_repeat1] = aux_sym_parameter_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_group_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_property_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_CR_LF2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_parameter_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_property_name] = {
    .visible = true,
    .named = true,
  },
  [sym_property_value] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_name] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_property_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_property_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead > 0x1f &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead > 0x1f) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead > 0x1f &&
          lookahead != '"') ADVANCE(4);
      END_STATE();
    case 6:
      if (eof) ADVANCE(8);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == ':') ADVANCE(13);
      if (lookahead == ';') ADVANCE(12);
      if (lookahead == '=') ADVANCE(18);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      if (lookahead == '\t') ADVANCE(17);
      if (lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_group_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_property_value_token1);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_CR_LF2);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_CR_LF_TAB);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_parameter_value_token1);
      if (lookahead > 0x1f &&
          lookahead != '"' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_parameter_value_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 7},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_CR_LF] = ACTIONS(3),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_group_token1] = ACTIONS(1),
    [aux_sym_property_value_token1] = ACTIONS(1),
    [anon_sym_CR_LF2] = ACTIONS(1),
    [anon_sym_CR_LF_TAB] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(31),
    [sym_property] = STATE(36),
    [sym_group] = STATE(35),
    [sym_property_name] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_CR_LF] = ACTIONS(7),
    [aux_sym_group_token1] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(9), 1,
      aux_sym_group_token1,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(13), 1,
      sym_property_name,
    STATE(28), 1,
      sym_property,
    STATE(35), 1,
      sym_group,
  [22] = 7,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      aux_sym_group_token1,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(13), 1,
      sym_property_name,
    STATE(35), 1,
      sym_group,
    STATE(38), 1,
      sym_property,
  [44] = 4,
    ACTIONS(18), 1,
      ts_builtin_sym_end,
    ACTIONS(20), 1,
      anon_sym_CR_LF,
    STATE(4), 1,
      aux_sym_property_value_repeat1,
    ACTIONS(22), 3,
      aux_sym_property_value_token1,
      anon_sym_CR_LF2,
      anon_sym_CR_LF_TAB,
  [59] = 4,
    ACTIONS(3), 1,
      anon_sym_CR_LF,
    STATE(7), 1,
      aux_sym_property_value_repeat1,
    STATE(34), 1,
      sym_property_value,
    ACTIONS(25), 3,
      aux_sym_property_value_token1,
      anon_sym_CR_LF2,
      anon_sym_CR_LF_TAB,
  [74] = 4,
    ACTIONS(3), 1,
      anon_sym_CR_LF,
    STATE(7), 1,
      aux_sym_property_value_repeat1,
    STATE(30), 1,
      sym_property_value,
    ACTIONS(25), 3,
      aux_sym_property_value_token1,
      anon_sym_CR_LF2,
      anon_sym_CR_LF_TAB,
  [89] = 4,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      anon_sym_CR_LF,
    STATE(4), 1,
      aux_sym_property_value_repeat1,
    ACTIONS(31), 3,
      aux_sym_property_value_token1,
      anon_sym_CR_LF2,
      anon_sym_CR_LF_TAB,
  [104] = 4,
    ACTIONS(3), 1,
      anon_sym_CR_LF,
    STATE(7), 1,
      aux_sym_property_value_repeat1,
    STATE(33), 1,
      sym_property_value,
    ACTIONS(25), 3,
      aux_sym_property_value_token1,
      anon_sym_CR_LF2,
      anon_sym_CR_LF_TAB,
  [119] = 4,
    ACTIONS(3), 1,
      anon_sym_CR_LF,
    STATE(7), 1,
      aux_sym_property_value_repeat1,
    STATE(37), 1,
      sym_property_value,
    ACTIONS(25), 3,
      aux_sym_property_value_token1,
      anon_sym_CR_LF2,
      anon_sym_CR_LF_TAB,
  [134] = 4,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    STATE(11), 1,
      aux_sym_parameter_repeat1,
    ACTIONS(33), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [148] = 4,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(35), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      aux_sym_parameter_repeat1,
    ACTIONS(37), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [162] = 4,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(41), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      aux_sym_parameter_repeat1,
    ACTIONS(39), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [176] = 4,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(44), 1,
      anon_sym_SEMI,
    ACTIONS(46), 1,
      anon_sym_COLON,
    STATE(14), 1,
      aux_sym_property_repeat1,
  [189] = 4,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(44), 1,
      anon_sym_SEMI,
    ACTIONS(48), 1,
      anon_sym_COLON,
    STATE(16), 1,
      aux_sym_property_repeat1,
  [202] = 4,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(44), 1,
      anon_sym_SEMI,
    ACTIONS(50), 1,
      anon_sym_COLON,
    STATE(17), 1,
      aux_sym_property_repeat1,
  [215] = 4,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(52), 1,
      anon_sym_SEMI,
    ACTIONS(55), 1,
      anon_sym_COLON,
    STATE(16), 1,
      aux_sym_property_repeat1,
  [228] = 4,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(44), 1,
      anon_sym_SEMI,
    ACTIONS(57), 1,
      anon_sym_COLON,
    STATE(16), 1,
      aux_sym_property_repeat1,
  [241] = 3,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    STATE(10), 1,
      sym_parameter_value,
    ACTIONS(59), 2,
      aux_sym_parameter_value_token1,
      aux_sym_parameter_value_token2,
  [252] = 2,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(61), 3,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_COMMA,
  [261] = 3,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(63), 1,
      anon_sym_DOT,
    ACTIONS(65), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [272] = 4,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(67), 1,
      aux_sym_group_token1,
    STATE(25), 1,
      sym_parameter,
    STATE(32), 1,
      sym_parameter_name,
  [285] = 2,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(39), 3,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_COMMA,
  [294] = 3,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    STATE(22), 1,
      sym_parameter_value,
    ACTIONS(59), 2,
      aux_sym_parameter_value_token1,
      aux_sym_parameter_value_token2,
  [305] = 2,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(65), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [313] = 2,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(55), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [321] = 3,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(69), 1,
      aux_sym_group_token1,
    STATE(15), 1,
      sym_property_name,
  [331] = 2,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(13), 2,
      ts_builtin_sym_end,
      aux_sym_group_token1,
  [339] = 2,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      anon_sym_CR_LF,
  [346] = 2,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(75), 1,
      anon_sym_EQ,
  [353] = 1,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
  [358] = 2,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
  [365] = 2,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(81), 1,
      anon_sym_EQ,
  [372] = 1,
    ACTIONS(83), 2,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
  [377] = 1,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
  [382] = 2,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(87), 1,
      anon_sym_DOT,
  [389] = 2,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      anon_sym_CR_LF,
  [396] = 1,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
  [401] = 1,
    ACTIONS(73), 1,
      anon_sym_CR_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 44,
  [SMALL_STATE(5)] = 59,
  [SMALL_STATE(6)] = 74,
  [SMALL_STATE(7)] = 89,
  [SMALL_STATE(8)] = 104,
  [SMALL_STATE(9)] = 119,
  [SMALL_STATE(10)] = 134,
  [SMALL_STATE(11)] = 148,
  [SMALL_STATE(12)] = 162,
  [SMALL_STATE(13)] = 176,
  [SMALL_STATE(14)] = 189,
  [SMALL_STATE(15)] = 202,
  [SMALL_STATE(16)] = 215,
  [SMALL_STATE(17)] = 228,
  [SMALL_STATE(18)] = 241,
  [SMALL_STATE(19)] = 252,
  [SMALL_STATE(20)] = 261,
  [SMALL_STATE(21)] = 272,
  [SMALL_STATE(22)] = 285,
  [SMALL_STATE(23)] = 294,
  [SMALL_STATE(24)] = 305,
  [SMALL_STATE(25)] = 313,
  [SMALL_STATE(26)] = 321,
  [SMALL_STATE(27)] = 331,
  [SMALL_STATE(28)] = 339,
  [SMALL_STATE(29)] = 346,
  [SMALL_STATE(30)] = 353,
  [SMALL_STATE(31)] = 358,
  [SMALL_STATE(32)] = 365,
  [SMALL_STATE(33)] = 372,
  [SMALL_STATE(34)] = 377,
  [SMALL_STATE(35)] = 382,
  [SMALL_STATE(36)] = 389,
  [SMALL_STATE(37)] = 396,
  [SMALL_STATE(38)] = 401,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_property_value_repeat1, 2, 0, 0),
  [20] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_property_value_repeat1, 2, 0, 0),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_property_value_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_value, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_value, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 4, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_property_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_property_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_value, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_name, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_name, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 6, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 5, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vcard(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "vcard",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
