/* Automatically generated by tree-sitter v0.25.1 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 45
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_CR_LF = 1,
  anon_sym_DOT = 2,
  anon_sym_SEMI = 3,
  anon_sym_COLON = 4,
  aux_sym_group_token1 = 5,
  sym_property_value = 6,
  anon_sym_EQ = 7,
  anon_sym_COMMA = 8,
  aux_sym_parameter_value_token1 = 9,
  aux_sym_parameter_value_token2 = 10,
  sym_source_file = 11,
  sym__crlf = 12,
  sym_property = 13,
  sym_group = 14,
  sym_property_name = 15,
  sym_parameter = 16,
  sym_parameter_name = 17,
  sym_parameter_value = 18,
  aux_sym_source_file_repeat1 = 19,
  aux_sym_source_file_repeat2 = 20,
  aux_sym_property_repeat1 = 21,
  aux_sym_parameter_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_DOT] = ".",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [aux_sym_group_token1] = "group_token1",
  [sym_property_value] = "property_value",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [aux_sym_parameter_value_token1] = "parameter_value_token1",
  [aux_sym_parameter_value_token2] = "parameter_value_token2",
  [sym_source_file] = "source_file",
  [sym__crlf] = "_crlf",
  [sym_property] = "property",
  [sym_group] = "group",
  [sym_property_name] = "property_name",
  [sym_parameter] = "parameter",
  [sym_parameter_name] = "parameter_name",
  [sym_parameter_value] = "parameter_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_property_repeat1] = "property_repeat1",
  [aux_sym_parameter_repeat1] = "parameter_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_group_token1] = aux_sym_group_token1,
  [sym_property_value] = sym_property_value,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_parameter_value_token1] = aux_sym_parameter_value_token1,
  [aux_sym_parameter_value_token2] = aux_sym_parameter_value_token2,
  [sym_source_file] = sym_source_file,
  [sym__crlf] = sym__crlf,
  [sym_property] = sym_property,
  [sym_group] = sym_group,
  [sym_property_name] = sym_property_name,
  [sym_parameter] = sym_parameter,
  [sym_parameter_name] = sym_parameter_name,
  [sym_parameter_value] = sym_parameter_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_property_repeat1] = aux_sym_property_repeat1,
  [aux_sym_parameter_repeat1] = aux_sym_parameter_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_group_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_property_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_parameter_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__crlf] = {
    .visible = false,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_property_name] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_name] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_property_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 9,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == ',') ADVANCE(16);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == ';') ADVANCE(10);
      if (lookahead == '=') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == '\r') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead == '"') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(3);
      if (lookahead > ' ' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead > 0x1f) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead > 0x1f &&
          lookahead != '"') ADVANCE(4);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '\r') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(6);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_group_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_property_value);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_property_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_parameter_value_token1);
      if (lookahead == ' ') ADVANCE(17);
      if (lookahead > ' ' &&
          lookahead != '"' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_parameter_value_token1);
      if (lookahead > 0x1f &&
          lookahead != '"' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != ';') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_parameter_value_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 13},
  [41] = {.lex_state = 13},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 13},
  [44] = {.lex_state = 13},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_group_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_parameter_value_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(39),
    [sym__crlf] = STATE(2),
    [sym_property] = STATE(10),
    [sym_group] = STATE(42),
    [sym_property_name] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_source_file_repeat2] = STATE(5),
    [anon_sym_CR_LF] = ACTIONS(3),
    [aux_sym_group_token1] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(5), 1,
      aux_sym_group_token1,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    STATE(4), 1,
      aux_sym_source_file_repeat2,
    STATE(11), 1,
      sym_property,
    STATE(18), 1,
      sym_property_name,
    STATE(42), 1,
      sym_group,
    STATE(12), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
  [23] = 4,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      anon_sym_CR_LF,
    ACTIONS(13), 1,
      aux_sym_group_token1,
    STATE(9), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
  [37] = 5,
    ACTIONS(15), 1,
      aux_sym_group_token1,
    STATE(6), 1,
      aux_sym_source_file_repeat2,
    STATE(15), 1,
      sym_property,
    STATE(18), 1,
      sym_property_name,
    STATE(42), 1,
      sym_group,
  [53] = 5,
    ACTIONS(15), 1,
      aux_sym_group_token1,
    STATE(6), 1,
      aux_sym_source_file_repeat2,
    STATE(11), 1,
      sym_property,
    STATE(18), 1,
      sym_property_name,
    STATE(42), 1,
      sym_group,
  [69] = 5,
    ACTIONS(17), 1,
      aux_sym_group_token1,
    STATE(6), 1,
      aux_sym_source_file_repeat2,
    STATE(18), 1,
      sym_property_name,
    STATE(26), 1,
      sym_property,
    STATE(42), 1,
      sym_group,
  [85] = 4,
    ACTIONS(11), 1,
      anon_sym_CR_LF,
    ACTIONS(13), 1,
      aux_sym_group_token1,
    ACTIONS(20), 1,
      ts_builtin_sym_end,
    STATE(9), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
  [99] = 4,
    ACTIONS(11), 1,
      anon_sym_CR_LF,
    ACTIONS(13), 1,
      aux_sym_group_token1,
    ACTIONS(22), 1,
      ts_builtin_sym_end,
    STATE(9), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
  [113] = 4,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
    ACTIONS(26), 1,
      anon_sym_CR_LF,
    ACTIONS(29), 1,
      aux_sym_group_token1,
    STATE(9), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
  [127] = 3,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_CR_LF,
    STATE(3), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
  [138] = 3,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_CR_LF,
    STATE(7), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
  [149] = 3,
    ACTIONS(29), 1,
      aux_sym_group_token1,
    ACTIONS(37), 1,
      anon_sym_CR_LF,
    STATE(12), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
  [160] = 3,
    ACTIONS(42), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym_parameter_repeat1,
    ACTIONS(40), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [171] = 3,
    ACTIONS(42), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym_parameter_repeat1,
    ACTIONS(44), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [182] = 3,
    ACTIONS(20), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 1,
      anon_sym_CR_LF,
    STATE(8), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
  [193] = 3,
    ACTIONS(7), 1,
      anon_sym_CR_LF,
    ACTIONS(13), 1,
      aux_sym_group_token1,
    STATE(12), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
  [204] = 3,
    ACTIONS(50), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      aux_sym_parameter_repeat1,
    ACTIONS(48), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [215] = 3,
    ACTIONS(53), 1,
      anon_sym_SEMI,
    ACTIONS(55), 1,
      anon_sym_COLON,
    STATE(20), 1,
      aux_sym_property_repeat1,
  [225] = 3,
    ACTIONS(57), 1,
      aux_sym_group_token1,
    STATE(33), 1,
      sym_parameter,
    STATE(38), 1,
      sym_parameter_name,
  [235] = 3,
    ACTIONS(53), 1,
      anon_sym_SEMI,
    ACTIONS(59), 1,
      anon_sym_COLON,
    STATE(23), 1,
      aux_sym_property_repeat1,
  [245] = 2,
    ACTIONS(61), 1,
      anon_sym_DOT,
    ACTIONS(63), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [253] = 3,
    ACTIONS(53), 1,
      anon_sym_SEMI,
    ACTIONS(65), 1,
      anon_sym_COLON,
    STATE(24), 1,
      aux_sym_property_repeat1,
  [263] = 3,
    ACTIONS(67), 1,
      anon_sym_SEMI,
    ACTIONS(70), 1,
      anon_sym_COLON,
    STATE(23), 1,
      aux_sym_property_repeat1,
  [273] = 3,
    ACTIONS(53), 1,
      anon_sym_SEMI,
    ACTIONS(72), 1,
      anon_sym_COLON,
    STATE(23), 1,
      aux_sym_property_repeat1,
  [283] = 1,
    ACTIONS(74), 3,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_COMMA,
  [289] = 2,
    ACTIONS(76), 1,
      anon_sym_CR_LF,
    STATE(16), 2,
      sym__crlf,
      aux_sym_source_file_repeat1,
  [297] = 3,
    ACTIONS(78), 1,
      aux_sym_parameter_value_token1,
    ACTIONS(80), 1,
      aux_sym_parameter_value_token2,
    STATE(29), 1,
      sym_parameter_value,
  [307] = 3,
    ACTIONS(78), 1,
      aux_sym_parameter_value_token1,
    ACTIONS(80), 1,
      aux_sym_parameter_value_token2,
    STATE(13), 1,
      sym_parameter_value,
  [317] = 1,
    ACTIONS(48), 3,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_COMMA,
  [323] = 1,
    ACTIONS(82), 2,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
  [328] = 1,
    ACTIONS(84), 2,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
  [333] = 1,
    ACTIONS(86), 2,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
  [338] = 1,
    ACTIONS(70), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [343] = 1,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
  [348] = 1,
    ACTIONS(63), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
  [353] = 2,
    ACTIONS(90), 1,
      aux_sym_group_token1,
    STATE(22), 1,
      sym_property_name,
  [360] = 1,
    ACTIONS(92), 1,
      anon_sym_EQ,
  [364] = 1,
    ACTIONS(94), 1,
      anon_sym_EQ,
  [368] = 1,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
  [372] = 1,
    ACTIONS(98), 1,
      sym_property_value,
  [376] = 1,
    ACTIONS(100), 1,
      sym_property_value,
  [380] = 1,
    ACTIONS(102), 1,
      anon_sym_DOT,
  [384] = 1,
    ACTIONS(104), 1,
      sym_property_value,
  [388] = 1,
    ACTIONS(106), 1,
      sym_property_value,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 23,
  [SMALL_STATE(4)] = 37,
  [SMALL_STATE(5)] = 53,
  [SMALL_STATE(6)] = 69,
  [SMALL_STATE(7)] = 85,
  [SMALL_STATE(8)] = 99,
  [SMALL_STATE(9)] = 113,
  [SMALL_STATE(10)] = 127,
  [SMALL_STATE(11)] = 138,
  [SMALL_STATE(12)] = 149,
  [SMALL_STATE(13)] = 160,
  [SMALL_STATE(14)] = 171,
  [SMALL_STATE(15)] = 182,
  [SMALL_STATE(16)] = 193,
  [SMALL_STATE(17)] = 204,
  [SMALL_STATE(18)] = 215,
  [SMALL_STATE(19)] = 225,
  [SMALL_STATE(20)] = 235,
  [SMALL_STATE(21)] = 245,
  [SMALL_STATE(22)] = 253,
  [SMALL_STATE(23)] = 263,
  [SMALL_STATE(24)] = 273,
  [SMALL_STATE(25)] = 283,
  [SMALL_STATE(26)] = 289,
  [SMALL_STATE(27)] = 297,
  [SMALL_STATE(28)] = 307,
  [SMALL_STATE(29)] = 317,
  [SMALL_STATE(30)] = 323,
  [SMALL_STATE(31)] = 328,
  [SMALL_STATE(32)] = 333,
  [SMALL_STATE(33)] = 338,
  [SMALL_STATE(34)] = 343,
  [SMALL_STATE(35)] = 348,
  [SMALL_STATE(36)] = 353,
  [SMALL_STATE(37)] = 360,
  [SMALL_STATE(38)] = 364,
  [SMALL_STATE(39)] = 368,
  [SMALL_STATE(40)] = 372,
  [SMALL_STATE(41)] = 376,
  [SMALL_STATE(42)] = 380,
  [SMALL_STATE(43)] = 384,
  [SMALL_STATE(44)] = 388,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(21),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 4, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_name, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_property_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_property_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_value, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 5, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 6, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_name, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [96] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vcard(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
